[2022-12-28T08:22:23.072+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: new_table_and_data_import_dag_v1.get_cash_flow_data manual__2022-12-28T08:22:10.389355+00:00 [queued]>
[2022-12-28T08:22:23.116+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: new_table_and_data_import_dag_v1.get_cash_flow_data manual__2022-12-28T08:22:10.389355+00:00 [queued]>
[2022-12-28T08:22:23.117+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-28T08:22:23.118+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2022-12-28T08:22:23.119+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-28T08:22:23.231+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): get_cash_flow_data> on 2022-12-28 08:22:10.389355+00:00
[2022-12-28T08:22:23.245+0000] {standard_task_runner.py:55} INFO - Started process 4428 to run task
[2022-12-28T08:22:23.258+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'new_table_and_data_import_dag_v1', 'get_cash_flow_data', 'manual__2022-12-28T08:22:10.389355+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/new_table_and_data_import_dag.py', '--cfg-path', '/tmp/tmp53qct74k']
[2022-12-28T08:22:23.264+0000] {standard_task_runner.py:83} INFO - Job 25: Subtask get_cash_flow_data
[2022-12-28T08:22:23.545+0000] {task_command.py:389} INFO - Running <TaskInstance: new_table_and_data_import_dag_v1.get_cash_flow_data manual__2022-12-28T08:22:10.389355+00:00 [running]> on host 016cb28b89a1
[2022-12-28T08:22:24.325+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=new_table_and_data_import_dag_v1
AIRFLOW_CTX_TASK_ID=get_cash_flow_data
AIRFLOW_CTX_EXECUTION_DATE=2022-12-28T08:22:10.389355+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-28T08:22:10.389355+00:00
[2022-12-28T08:22:25.444+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/new_table_and_data_import_dag.py", line 31, in get_cash_flow
    cash_flow = financial_flow ('AAA', 'cashflow' ,'quarterly')
  File "/home/airflow/.local/lib/python3.7/site-packages/vnstock/stock.py", line 214, in financial_flow
    data = requests.get('https://apipubaws.tcbs.com.vn/tcanalysis/v1/finance/{}/{}'.format(symbol, report_type), params={'yearly': x, 'isAll':'true'}).json()
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2022-12-28T08:22:25.480+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=new_table_and_data_import_dag_v1, task_id=get_cash_flow_data, execution_date=20221228T082210, start_date=20221228T082223, end_date=20221228T082225
[2022-12-28T08:22:25.568+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 25 for task get_cash_flow_data (Expecting value: line 1 column 1 (char 0); 4428)
[2022-12-28T08:22:25.634+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-12-28T08:22:25.886+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
