[2022-12-31T12:55:19.337+0000] {processor.py:153} INFO - Started process (PID=527) to work on /opt/airflow/dags/import_by_csv.py
[2022-12-31T12:55:19.338+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/import_by_csv.py for tasks to queue
[2022-12-31T12:55:19.339+0000] {logging_mixin.py:137} INFO - [2022-12-31T12:55:19.339+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/import_by_csv.py
[2022-12-31T12:55:58.054+0000] {logging_mixin.py:137} INFO - [2022-12-31T12:55:58.053+0000] {timeout.py:68} ERROR - Process timed out, PID: 527
[2022-12-31T12:56:00.381+0000] {logging_mixin.py:137} INFO - [2022-12-31T12:55:58.055+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/import_by_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/import_by_csv.py", line 6, in <module>
    from vnstock import *
  File "/home/airflow/.local/lib/python3.7/site-packages/vnstock/__init__.py", line 7, in <module>
    from .stock import *
  File "/home/airflow/.local/lib/python3.7/site-packages/vnstock/stock.py", line 4, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/__init__.py", line 23, in <module>
    from pandas.compat.pyarrow import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/pyarrow.py", line 6, in <module>
    import pyarrow as pa
  File "/home/airflow/.local/lib/python3.7/site-packages/pyarrow/__init__.py", line 65, in <module>
    import pyarrow.lib as _lib
  File "<frozen importlib._bootstrap>", line 416, in parent
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/import_by_csv.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.5.0/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.5.0/best-practices.html#reducing-dag-complexity, PID: 527
[2022-12-31T12:56:00.383+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/import_by_csv.py
[2022-12-31T12:56:02.095+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/import_by_csv.py took 42.762 seconds
[2022-12-31T12:56:32.901+0000] {processor.py:153} INFO - Started process (PID=639) to work on /opt/airflow/dags/import_by_csv.py
[2022-12-31T12:56:33.149+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/import_by_csv.py for tasks to queue
[2022-12-31T12:56:33.150+0000] {logging_mixin.py:137} INFO - [2022-12-31T12:56:33.150+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/import_by_csv.py
[2022-12-31T12:57:03.222+0000] {logging_mixin.py:137} INFO - [2022-12-31T12:57:03.215+0000] {timeout.py:68} ERROR - Process timed out, PID: 639
[2022-12-31T12:57:03.231+0000] {logging_mixin.py:137} INFO - [2022-12-31T12:57:03.223+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/import_by_csv.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/import_by_csv.py", line 6, in <module>
    from vnstock import *
  File "/home/airflow/.local/lib/python3.7/site-packages/vnstock/__init__.py", line 7, in <module>
    from .stock import *
  File "/home/airflow/.local/lib/python3.7/site-packages/vnstock/stock.py", line 4, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 143, in <module>
    from pandas.io.api import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/api.py", line 39, in <module>
    from pandas.io.stata import read_stata
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 818, in get_code
  File "<frozen importlib._bootstrap_external>", line 917, in get_data
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/import_by_csv.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.5.0/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.5.0/best-practices.html#reducing-dag-complexity, PID: 639
[2022-12-31T12:57:03.232+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/import_by_csv.py
[2022-12-31T12:57:03.556+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/import_by_csv.py took 30.660 seconds
